name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: KIDP2H
          GIST_ID: bceaaa9323f735f1fce04c289fbac0ae
          TIMEZONE: Asia/Ho_Chi_Minh
